version: '3.9'

services:
    postgres:
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile
        environment:
            - POSTGRES_PASSWORD=testpass
        volumes:
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"

    web:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
        depends_on:
            - postgres
            - redis

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        depends_on:
            - web
            - postgres
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./static/:/static/
            - ./media/:/media/
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

    redis:
        image: "redis:alpine"
        ports:
            - '6379:6379'
        restart: always
