# Generated by Django 3.1.7 on 2021-02-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'permissions': (('can_add_post', 'Can add post'),), 'verbose_name': 'Посты', 'verbose_name_plural': 'Пост'},
        ),
    ]
