# Generated by Django 3.1.5 on 2021-03-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
