# Generated by Django 3.1.5 on 2021-03-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
    ]
