# Generated by Django 3.2.9 on 2021-12-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
